// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go

// Package service_user_mails_test is a generated GoMock package.
package service_user_mails_test

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockStorageUserMails is a mock of StorageUserMails interface.
type MockStorageUserMails struct {
	ctrl     *gomock.Controller
	recorder *MockStorageUserMailsMockRecorder
}

// MockStorageUserMailsMockRecorder is the mock recorder for MockStorageUserMails.
type MockStorageUserMailsMockRecorder struct {
	mock *MockStorageUserMails
}

// NewMockStorageUserMails creates a new mock instance.
func NewMockStorageUserMails(ctrl *gomock.Controller) *MockStorageUserMails {
	mock := &MockStorageUserMails{ctrl: ctrl}
	mock.recorder = &MockStorageUserMailsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageUserMails) EXPECT() *MockStorageUserMailsMockRecorder {
	return m.recorder
}

// ExistByEmail mocks base method.
func (m *MockStorageUserMails) ExistByEmail(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistByEmail", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistByEmail indicates an expected call of ExistByEmail.
func (mr *MockStorageUserMailsMockRecorder) ExistByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistByEmail", reflect.TypeOf((*MockStorageUserMails)(nil).ExistByEmail), ctx, email)
}

// GetUserIdByEmail mocks base method.
func (m *MockStorageUserMails) GetUserIdByEmail(ctx context.Context, email string) (*uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIdByEmail", ctx, email)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIdByEmail indicates an expected call of GetUserIdByEmail.
func (mr *MockStorageUserMailsMockRecorder) GetUserIdByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIdByEmail", reflect.TypeOf((*MockStorageUserMails)(nil).GetUserIdByEmail), ctx, email)
}
