// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go

// Package usecase_login_test is a generated GoMock package.
package usecase_login_test

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockServiceUsers is a mock of ServiceUsers interface.
type MockServiceUsers struct {
	ctrl     *gomock.Controller
	recorder *MockServiceUsersMockRecorder
}

// MockServiceUsersMockRecorder is the mock recorder for MockServiceUsers.
type MockServiceUsersMockRecorder struct {
	mock *MockServiceUsers
}

// NewMockServiceUsers creates a new mock instance.
func NewMockServiceUsers(ctrl *gomock.Controller) *MockServiceUsers {
	mock := &MockServiceUsers{ctrl: ctrl}
	mock.recorder = &MockServiceUsersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceUsers) EXPECT() *MockServiceUsersMockRecorder {
	return m.recorder
}

// CreateWithEmail mocks base method.
func (m *MockServiceUsers) CreateWithEmail(ctx context.Context, email string) (*uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithEmail", ctx, email)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWithEmail indicates an expected call of CreateWithEmail.
func (mr *MockServiceUsersMockRecorder) CreateWithEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithEmail", reflect.TypeOf((*MockServiceUsers)(nil).CreateWithEmail), ctx, email)
}

// MockServiceUserMails is a mock of ServiceUserMails interface.
type MockServiceUserMails struct {
	ctrl     *gomock.Controller
	recorder *MockServiceUserMailsMockRecorder
}

// MockServiceUserMailsMockRecorder is the mock recorder for MockServiceUserMails.
type MockServiceUserMailsMockRecorder struct {
	mock *MockServiceUserMails
}

// NewMockServiceUserMails creates a new mock instance.
func NewMockServiceUserMails(ctrl *gomock.Controller) *MockServiceUserMails {
	mock := &MockServiceUserMails{ctrl: ctrl}
	mock.recorder = &MockServiceUserMailsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceUserMails) EXPECT() *MockServiceUserMailsMockRecorder {
	return m.recorder
}

// ExistsByEmail mocks base method.
func (m *MockServiceUserMails) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByEmail", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByEmail indicates an expected call of ExistsByEmail.
func (mr *MockServiceUserMailsMockRecorder) ExistsByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByEmail", reflect.TypeOf((*MockServiceUserMails)(nil).ExistsByEmail), ctx, email)
}

// GetUserIdByEmail mocks base method.
func (m *MockServiceUserMails) GetUserIdByEmail(ctx context.Context, email string) (*uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIdByEmail", ctx, email)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIdByEmail indicates an expected call of GetUserIdByEmail.
func (mr *MockServiceUserMailsMockRecorder) GetUserIdByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIdByEmail", reflect.TypeOf((*MockServiceUserMails)(nil).GetUserIdByEmail), ctx, email)
}

// MockQueueConfirmationCodeRequested is a mock of QueueConfirmationCodeRequested interface.
type MockQueueConfirmationCodeRequested struct {
	ctrl     *gomock.Controller
	recorder *MockQueueConfirmationCodeRequestedMockRecorder
}

// MockQueueConfirmationCodeRequestedMockRecorder is the mock recorder for MockQueueConfirmationCodeRequested.
type MockQueueConfirmationCodeRequestedMockRecorder struct {
	mock *MockQueueConfirmationCodeRequested
}

// NewMockQueueConfirmationCodeRequested creates a new mock instance.
func NewMockQueueConfirmationCodeRequested(ctrl *gomock.Controller) *MockQueueConfirmationCodeRequested {
	mock := &MockQueueConfirmationCodeRequested{ctrl: ctrl}
	mock.recorder = &MockQueueConfirmationCodeRequestedMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueConfirmationCodeRequested) EXPECT() *MockQueueConfirmationCodeRequestedMockRecorder {
	return m.recorder
}

// Produce mocks base method.
func (m *MockQueueConfirmationCodeRequested) Produce(ctx context.Context, userID, confirmationID, confirmationToken uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Produce", ctx, userID, confirmationID, confirmationToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Produce indicates an expected call of Produce.
func (mr *MockQueueConfirmationCodeRequestedMockRecorder) Produce(ctx, userID, confirmationID, confirmationToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockQueueConfirmationCodeRequested)(nil).Produce), ctx, userID, confirmationID, confirmationToken)
}
