openapi: 3.0.0

info:
    title: |
        Planify app API interface
    version: 1.0.0

paths:
    /habit/{id}:
        get:
            operationId: habitGet
            parameters:
                -   in: path
                    name: id
                    schema:
                        type: string
                        format: uuid
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HabitGetOut'
                    description: Habit get result
        put:
            operationId: habitUpdate
            parameters:
                -   in: path
                    name: id
                    schema:
                        type: string
                        format: uuid
                    required: true
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Habit'
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HabitUpdateOut'
                    description: Habit update result

components:
    schemas:
        Error:
            type: object
            required:
                - message
            properties:
                message:
                    type: string

        Habit:
            type: object
            required:
                - id
                - name
                - user_id
                - chat_id
                - canceled
                - created_at
            properties:
                id:
                    type: string
                    format: uuid
                name:
                    type: string
                    nullable: true
                user_id:
                    type: integer
                    format: int64
                chat_id:
                    type: integer
                    format: int64
                canceled:
                    type: boolean
                created_at:
                    type: string
                    format: date-time
        
        HabitGetOut:
            type:
                object
            properties:
                err: 
                    $ref: '#/components/schemas/Error'
                habit:
                    $ref: '#/components/schemas/Habit'

        HabitUpdateOut:
            type: 
                object
            properties:
                err:
                    $ref: '#/components/schemas/Error'
                habit:
                    $ref: '#/components/schemas/Habit'
