openapi: 3.0.0

info:
    title: |
        Planify app API interface
    version: 1.0.0

paths:
    /login:
        post:
            operationId: login
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginIn'
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginOut'
                    description: Login confirmation token

components:
    schemas:
        Email:
            type: string
            format: email

        ConfirmationToken:
            type: string
            format: uuid

        # request - responses

        LoginIn:
            type:
                object
            required:
                - email
            properties:
                email:
                    $ref: '#/components/schemas/Email'

        LoginOut:
            type: object
            required:
                - confirmationToken
            properties:
                confirmationToken:
                    $ref: '#/components/schemas/ConfirmationToken'
