// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go

// Package service_users_test is a generated GoMock package.
package service_users_test

import (
	context "context"
	sql "database/sql"
	internal "pets-planify/internal"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockTx is a mock of Tx interface.
type MockTx struct {
	ctrl     *gomock.Controller
	recorder *MockTxMockRecorder
}

// MockTxMockRecorder is the mock recorder for MockTx.
type MockTxMockRecorder struct {
	mock *MockTx
}

// NewMockTx creates a new mock instance.
func NewMockTx(ctrl *gomock.Controller) *MockTx {
	mock := &MockTx{ctrl: ctrl}
	mock.recorder = &MockTxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTx) EXPECT() *MockTxMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockTx) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockTxMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockTx)(nil).Commit))
}

// ExecContext mocks base method.
func (m *MockTx) ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecContext", varargs...)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecContext indicates an expected call of ExecContext.
func (mr *MockTxMockRecorder) ExecContext(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecContext", reflect.TypeOf((*MockTx)(nil).ExecContext), varargs...)
}

// Rollback mocks base method.
func (m *MockTx) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockTxMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockTx)(nil).Rollback))
}

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Tx mocks base method.
func (m *MockStorage) Tx() (internal.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tx")
	ret0, _ := ret[0].(internal.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tx indicates an expected call of Tx.
func (mr *MockStorageMockRecorder) Tx() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tx", reflect.TypeOf((*MockStorage)(nil).Tx))
}

// MockStorageUsers is a mock of StorageUsers interface.
type MockStorageUsers struct {
	ctrl     *gomock.Controller
	recorder *MockStorageUsersMockRecorder
}

// MockStorageUsersMockRecorder is the mock recorder for MockStorageUsers.
type MockStorageUsersMockRecorder struct {
	mock *MockStorageUsers
}

// NewMockStorageUsers creates a new mock instance.
func NewMockStorageUsers(ctrl *gomock.Controller) *MockStorageUsers {
	mock := &MockStorageUsers{ctrl: ctrl}
	mock.recorder = &MockStorageUsersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageUsers) EXPECT() *MockStorageUsersMockRecorder {
	return m.recorder
}

// CreateWithTx mocks base method.
func (m *MockStorageUsers) CreateWithTx(ctx context.Context, id uuid.UUID, tx internal.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTx", ctx, id, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithTx indicates an expected call of CreateWithTx.
func (mr *MockStorageUsersMockRecorder) CreateWithTx(ctx, id, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTx", reflect.TypeOf((*MockStorageUsers)(nil).CreateWithTx), ctx, id, tx)
}

// MockStorageUserMails is a mock of StorageUserMails interface.
type MockStorageUserMails struct {
	ctrl     *gomock.Controller
	recorder *MockStorageUserMailsMockRecorder
}

// MockStorageUserMailsMockRecorder is the mock recorder for MockStorageUserMails.
type MockStorageUserMailsMockRecorder struct {
	mock *MockStorageUserMails
}

// NewMockStorageUserMails creates a new mock instance.
func NewMockStorageUserMails(ctrl *gomock.Controller) *MockStorageUserMails {
	mock := &MockStorageUserMails{ctrl: ctrl}
	mock.recorder = &MockStorageUserMailsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageUserMails) EXPECT() *MockStorageUserMailsMockRecorder {
	return m.recorder
}

// CreateWithTx mocks base method.
func (m *MockStorageUserMails) CreateWithTx(ctx context.Context, userID uuid.UUID, email string, tx internal.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTx", ctx, userID, email, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithTx indicates an expected call of CreateWithTx.
func (mr *MockStorageUserMailsMockRecorder) CreateWithTx(ctx, userID, email, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTx", reflect.TypeOf((*MockStorageUserMails)(nil).CreateWithTx), ctx, userID, email, tx)
}
